apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teslamate.fullname" . }}
  labels:
    {{- include "teslamate.labels" . | nindent 4 }}
stringData:
  database_password: "{{ .Values.teslamate.database.password }}"
  grafana_password: "{{ .Values.grafana.password }}"
