apiVersion: v2
name: metrics-server
description: metrics-server deployment

type: application
version: 5.9.3
appVersion: 0.5.0

dependencies:
  - name: metrics-server
    version: 5.9.3
    repository: https://charts.bitnami.com/bitnami
