apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "postfix.fullname" . }}-certs
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "postfix.gen-certs" . ) | indent 2 }}
