apiVersion: v1
kind: Service
metadata:
  name: {{ include "postfix.fullname" . }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 25
      targetPort: 25
      protocol: TCP
      name: smtp
    - port: 587
      targetPort: 587
      protocol: TCP
      name: submission
  selector:
    {{- include "postfix.selectorLabels" . | nindent 4 }}
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
