apiVersion: v2
name: mqtt
description: mqtt Daemon

type: application
version: 4.4.0
appVersion: 2.0.11

dependencies:
  - name: mosquitto
    version: 4.4.0
    repository: https://k8s-at-home.com/charts/
