apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "penguin-nodes.fullname" . }}
  labels:
    {{- include "penguin-nodes.labels" . | nindent 4 }}
data:
  cacert.pem: |
{{ .Values.mqtt.cacert | indent 4 }}

