apiVersion: v1
kind: Secret
metadata:
  name: {{ include "penguin-nodes.fullname" . }}
  labels:
    {{- include "penguin-nodes.labels" . | nindent 4 }}
stringData:
  DATABASE_URL: {{  .Values.pn.database_url }}
  GUARDIAN_SECRET: {{ .Values.pn.guardian_secret }}
  SECRET_KEY_BASE: {{ .Values.pn.secret_key_base }}
  SIGNING_SALT: {{ .Values.pn.signing_salt }}
  MQTT_PASSWORD: {{ .Values.mqtt.password }}
  OIDC_CLIENT_ID: {{ .Values.oidc.client_id }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.client_secret }}
  LIFE360_PASSWORD: {{ .Values.life360.password }}
