apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "robotica-hello.fullname" . }}
  labels:
    {{- include "robotica-hello.labels" . | nindent 4 }}
data:
  hello.yaml: |
    instances:
      {{- toYaml .Values.robotica.instances | nindent 6 }}
