{{- with .Values.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "robotica-hello.fullname" $ }}
  labels:
    {{- include "robotica-hello.selectorLabels" $ | nindent 4 }}
    {{- include "robotica-hello.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "robotica-hello.selectorLabels" $ | nindent 6 }}
  {{- toYaml . | nindent 2 }}
{{- end }}
