apiVersion: v1
kind: Secret
metadata:
  name: {{ include "robotica-hello.fullname" . }}
  labels:
    {{- include "robotica-hello.labels" . | nindent 4 }}
stringData:
  DATABASE_URL: {{  .Values.robotica.database_url }}
  GUARDIAN_SECRET: {{ .Values.robotica.guardian_secret }}
  SECRET_KEY_BASE: {{ .Values.robotica.secret_key_base }}
  LOGIN_SECRET: {{ .Values.robotica.login_secret }}
