apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teslamate.fullname" . }}
  labels:
    {{- include "teslamate.labels" . | nindent 4 }}
stringData:
  database_password: "{{ .Values.teslamate.database.password }}"
  mqtt_password: "{{ .Values.teslamate.mqtt.password }}"
  encryption_key: "{{ .Values.teslamate.encryption_key }}"

