{{- if .Values.prometheusOperator.serviceMonitor.enable }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dex.fullname" . }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      targetPort: telemetry
      honorLabels: true
  selector:
    matchLabels:
      {{- include "dex.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
