apiVersion: v1
kind: Secret
metadata:
  name: {{ include "penguin-memories.fullname" . }}
  labels:
    {{- include "penguin-memories.labels" . | nindent 4 }}
stringData:
  DATABASE_URL: {{  .Values.pm.database_url }}
  GUARDIAN_SECRET: {{ .Values.pm.guardian_secret }}
  SECRET_KEY_BASE: {{ .Values.pm.secret_key_base }}
  SIGNING_SALT: {{ .Values.pm.signing_salt }}
