apiVersion: v2
name: ingress-nginx
description: ingress-nginx deployment

type: application
version: 4.0.19
appVersion: 1.1.3

dependencies:
  - name: ingress-nginx
    version: 4.0.19
    repository: https://kubernetes.github.io/ingress-nginx
