apiVersion: v2
name: ingress-nginx
description: ingress-nginx deployment

type: application
version: 4.1.4
appVersion: 1.2.1

dependencies:
  - name: ingress-nginx
    version: 4.1.4
    repository: https://kubernetes.github.io/ingress-nginx
