apiVersion: v2
name: ingress-nginx
description: ingress-nginx deployment

type: application
version: 4.4.0
appVersion: 1.5.1

dependencies:
  - name: ingress-nginx
    version: 4.4.0
    repository: https://kubernetes.github.io/ingress-nginx
