metallb:
    speaker:
        secretValue: ENC[AES256_GCM,data:21pOL3dOt9P2MUeaDjMNwhH4/gbEhOC5VHs5hdUqDQGeFpVqI/U7KadM4Zv7sdw4/LmPapKzGnoKQQVM50DvDQ3zp095ujIKpnbxI0Ykc/sPg4ZjbAMx5DW5WBKwPuq/g4fbdFx13qI9It/YXJeXmvjABjkCy/peMOoLWaoHrl86rAKwKUV7GSdwbWsL02PCaPdHZSkiuTNOXy7DeY6jVY2pCzrFCs7KnGc8EA3UpDTwvl3xHbVn+ka9FDUzS08fCgc/DoDo4TQmqBHlRsx/5G9PPNPk8HM+zRZYnuaVJeB4DAjN/WolP6ke19YJJAbfTwhBQhWgqNSqP5aF1bnwjw==,iv:AcBhjYYQswtWsHJKDJx6xsgLqWCaLyVAlIl3mBRZOdI=,tag:bST848GwgtSjlKMHSSvvvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-02T05:38:55Z'
    mac: ENC[AES256_GCM,data:2mNQW0fcjB5AzeIbRgJRYb925TYioHM3bi62o/yxY6/CtdczYyS/h8GrUjmIO52u0Nq3GcnN1/jKr8zoO+zdvIPBsCamETYWLL+SyAp3x9ILQ7BPrSZHuwGpDhTtOjICr5BPemJtE0KwXbtDFR+ZgH4RO6xH00/cdtQDj0TH8uk=,iv:cpCd0fHXttZBQXqtOFfFBLXj32RfqU2/vs8c5KKAEyQ=,tag:p5xLXX/xBKCCO6s6hI7kuQ==,type:str]
    pgp:
    -   created_at: '2021-02-02T05:38:02Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5XFR1vPE5cQARAAifI00IPyjQRGzwpah/1jE3ez4UlpYL6kQhG9Qs7sYDm4
            BGjvyXY8SpPHH8kmVQV/zLJry/BH9igLtfoVNlJJ0ZNWe4ZOb77fy2GRqvjfvJWf
            uWH/qDocEgu6X/zxPQAgxwfj/8Qzzbub5pVR14Lhl3Vd9qRoXgSbwsWMu9e8kkz1
            vyqMkdNgY8u87dyJOSV55Jgs5T2QwhG7n0lAWKpNbMSHsJb8QWMq+y3AwPLWy/TO
            5j2ZafouCN2/iRyfbEw3qoBo0u2qKhbYmdRn/eVcYWc7uM2dgimLCkLJMKeGs7hq
            mzwRC3mn11/ufSfR40vSzS4kNqnWzSjuBiZ/d8WA3Vc9jkOtc2HpgOXJIytUJeyv
            ND9gMbGixn0DvZWKHlNHYoHaefeLHR+nVhZFBlkKSa0eVQKFs6A3WDNgxXbFLYmW
            L+rf/6GUM225fkCHnY4M8l5So4whQWnFfqkhbeokE3BrEo9r1DHasOt4wkrZVtMz
            z6vX8zy+ljDqkLfMfrioPeJqUwi5C4yOHFHuHUciPxZP8CQBRE4f6vObbvZlpuj6
            3I/kvIxMaJIpnnawkTvIf9flYyHN1+UDKv3Kqpi2K9IsIUOSELd1WYJs44LSO4LH
            ijn1J9N8lkhZqfRcTwh66O1be7iSe+NuOrvNs9C31X0hdO/zySEdA2/SOnb+xDXS
            XAGWIM1UxLxV2IEipWpsV2ZrQhLWNK9Gu6Zw02BYaOlFz3I9eCdDzxkY8EywYup8
            IgWm/3ik9oep5fPmUnJu3iiesMZx4aU41Q3nYMXwt88x2tUIpLrzbrumTnjG
            =sM4a
            -----END PGP MESSAGE-----
        fp: D6365126A92DB560C627ACED1784577F811F6EAC
    unencrypted_suffix: _unencrypted
    version: 3.6.1
