apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "phonedb.fullname" . }}
  labels:
    {{- include "phonedb.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.deploymentAnnotations | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "phonedb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "phonedb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "phonedb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 4000
          startupProbe:
            httpGet:
              path: /
              port: 4000
            failureThreshold: 120
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
               fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KUBERNETES_SELECTOR
            value: "app.kubernetes.io/instance={{ include "phonedb.name" . }}"
          - name: RELEASE_COOKIE
            value: "{{ .Values.elixir_cookie }}"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ include "phonedb.fullname" . }}
                key: DATABASE_URL
          - name: GUARDIAN_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "phonedb.fullname" . }}
                key: GUARDIAN_SECRET
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: {{ include "phonedb.fullname" . }}
                key: SECRET_KEY_BASE
          - name: SIGNING_SALT
            valueFrom:
              secretKeyRef:
                name: {{ include "phonedb.fullname" . }}
                key: SIGNING_SALT
          - name: LDAP_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "phonedb.fullname" . }}
                key: LDAP_PASSWORD
          - name: HTTP_HOST
            value: "{{ .Values.phonedb.http_host }}"
          - name: HTTP_URL
            value: "{{ .Values.phonedb.http_url }}"
          - name: LDAP_SERVER
            value: "{{ .Values.ldap.server }}"
          - name: LDAP_BASE_DN
            value: "{{ .Values.ldap.base_dn }}"
          - name: LDAP_USERNAME
            value: "{{ .Values.ldap.user_name }}"
          - name: PHONE_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ include "phonedb.fullname" . }}
                key: PHONE_USERNAME
          - name: PHONE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "phonedb.fullname" . }}
                key: PHONE_WORD
          - name: OIDC_DISCOVERY_URL
            value: "{{ .Values.oidc.discovery_url }}"
          - name: OIDC_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: {{ include "phonedb.fullname" . }}
                key: OIDC_CLIENT_ID
          - name: OIDC_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "phonedb.fullname" . }}
                key: OIDC_CLIENT_SECRET
          - name: OIDC_AUTH_SCOPE
            value: "{{ .Values.oidc.auth_scope }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
