apiVersion: v1
kind: Secret
metadata:
  name: {{ include "phonedb.fullname" . }}
  labels:
    {{- include "phonedb.labels" . | nindent 4 }}
stringData:
  DATABASE_URL: {{  .Values.phonedb.database_url }}
  GUARDIAN_SECRET: {{ .Values.phonedb.guardian_secret }}
  SECRET_KEY_BASE: {{ .Values.phonedb.secret_key_base }}
  SIGNING_SALT: {{ .Values.phonedb.signing_salt }}
  LDAP_PASSWORD: {{ .Values.ldap.password }}
  OIDC_CLIENT_ID: {{ .Values.oidc.client_id }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.client_secret }}
  PHONE_USERNAME: {{ .Values.phonedb.phone_username }}
  PHONE_PASSWORD: {{ .Values.phonedb.phone_password }}
