# Default values for service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  enabled: false
  type: ClusterIP
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  app: webapp
  selector: {}

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []
  ingressClassName: ~

certificate:
  enabled: false
  commonName: ""
  secretName: ""
  organizations: []
  dnsNames: []
  issuerRef: {}
