{{- if .Values.certificate.enabled -}}
{{- $fullName := include "service.fullname" . -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  commonName: "{{- .Values.certificate.commonName}}"
  secretName: "{{- .Values.certificate.secretName }}"
  dnsNames:
    {{- toYaml .Values.certificate.dnsNames | nindent 4 }}
  subject:
    organizations:
      {{- toYaml .Values.certificate.organizations | nindent 6 }}
  issuerRef:
    {{- toYaml .Values.certificate.issuerRef | nindent 4 }}
{{- end }}
