apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scrooge.fullname" . }}
  labels:
    {{- include "scrooge.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.deploymentAnnotations | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "scrooge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "scrooge.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "scrooge.fullname" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "scrooge.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 4000
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
               fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KUBERNETES_SELECTOR
            value: "{{ .Values.kubernetes_selector }}"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ include "scrooge.fullname" . }}
                key: DATABASE_URL
          - name: GUARDIAN_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "scrooge.fullname" . }}
                key: GUARDIAN_SECRET
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: {{ include "scrooge.fullname" . }}
                key: SECRET_KEY_BASE
          - name: SIGNING_SALT
            valueFrom:
              secretKeyRef:
                name: {{ include "scrooge.fullname" . }}
                key: SIGNING_SALT
          - name: MQTT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "scrooge.fullname" . }}
                key: MQTT_PASSWORD
          - name: HTTP_HOST
            value: "{{ .Values.scrooge.http_host }}"
          - name: MQTT_HOST
            value: "{{ .Values.mqtt.host }}"
          - name: MQTT_PORT
            value: "{{ .Values.mqtt.port }}"
          - name: MQTT_USER_NAME
            value: "{{ .Values.mqtt.user_name }}"
          - name: MQTT_CA_CERT_FILE
            value: /etc/scrooge/cacert.pem
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config-volume
            mountPath: /etc/scrooge
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
