apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scrooge.fullname" . }}
  labels:
    {{- include "scrooge.labels" . | nindent 4 }}
stringData:
  DATABASE_URL: {{  .Values.scrooge.database_url }}
  GUARDIAN_SECRET: {{ .Values.scrooge.guardian_secret }}
  SECRET_KEY_BASE: {{ .Values.scrooge.secret_key_base }}
  SIGNING_SALT: {{ .Values.scrooge.signing_salt }}
  MQTT_PASSWORD: {{ .Values.mqtt.password }}
