apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "brian-node-rust.fullname" . }}
  labels:
    {{- include "brian-node-rust.labels" . | nindent 4 }}
data:
  cacert.pem: |
{{ .Values.mqtt.cacert | indent 4 }}

