apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brian-node-rust.fullname" . }}
  labels:
    {{- include "brian-node-rust.labels" . | nindent 4 }}
stringData:
  MQTT_PASSWORD: {{ .Values.mqtt.password }}
  LIFE360_PASSWORD: {{ .Values.life360.password }}
