{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "brian-node-rust.serviceAccountName" . }}
  labels:
    {{- include "brian-node-rust.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "brian-node-rust.serviceAccountName" . }}
  labels:
    {{- include "brian-node-rust.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "brian-node-rust.serviceAccountName" . }}
  labels:
    {{- include "brian-node-rust.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "brian-node-rust.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "brian-node-rust.serviceAccountName" . }}
{{- end }}
