apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mosquitto.fullname" . }}-secret
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
stringData:
  passwordfile: |-
    {{- .Values.authentication.passwordEntries | nindent 4 }}
