apiVersion: v2
name: home-assistant
description: home-assistant

type: application
version: 13.4.2
appVersion: 2022.5.4

dependencies:
  - name: home-assistant
    version: 13.4.2
    repository: https://k8s-at-home.com/charts/
