apiVersion: v2
name: cert-manager
description: cert-manager deployment

type: application
version: 1.6.0
appVersion: 1.6.0

dependencies:
  - name: cert-manager
    version: v1.6.0
    repository: https://charts.jetstack.io
