apiVersion: v2
name: cert-manager
description: cert-manager deployment

type: application
version: 1.5.3
appVersion: 1.5.3

dependencies:
  - name: cert-manager
    version: v1.5.3
    repository: https://charts.jetstack.io
