apiVersion: v2
name: cert-manager
description: cert-manager deployment

type: application
version: 1.8.2
appVersion: 1.8.2

dependencies:
  - name: cert-manager
    version: v1.8.2
    repository: https://charts.jetstack.io
