apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oidc-proxy.fullname" . }}
  labels:
    {{- include "oidc-proxy.labels" . | nindent 4 }}
stringData:
  OIDC_SESSION_SECRET: {{  .Values.session.secret }}
  OIDC_CLIENT_ID: {{ .Values.oidc.client_id }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.client_secret }}
