apiVersion: v1
kind: Secret
metadata:
  name: {{ include "robotica-docker.fullname" . }}
  labels:
    {{- include "robotica-docker.labels" . | nindent 4 }}
stringData:
  SECRET_KEY_BASE: {{ .Values.robotica.secret_key_base }}
  SIGNING_SALT: {{ .Values.robotica.signing_salt }}
  LOGIN_SECRET: {{ .Values.robotica.login_secret }}
  OIDC_CLIENT_ID: {{ .Values.oidc.client_id }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.client_secret }}