apiVersion: v1
kind: Service
metadata:
  name: {{ include "robotica-docker.fullname" . }}
  labels:
    {{- include "robotica-docker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    {{- include "robotica-docker.selectorLabels" . | nindent 4 }}
